#!/bin/bash
# 20-firewall
#
#  Install and configure Shorewall firewall
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

info " install and configure shoreline Firewall "

install_package shorewall

# enable shorewall
sed -i -e "s/startup=0/startup=1/" /etc/default/shorewall

if [ "$DISABLE_IPV6" == 'yes' ]; then
# - deshabilitar ipv6
sed -i "s/^DISABLE_IPV6=.*$/DISABLE_IPV6=Yes/" /etc/shorewall/shorewall.conf
fi
# optimize shorewall rules
sed -i "s/^OPTIMIZE=.*$/OPTIMIZE=8/" /etc/shorewall/shorewall.conf
sed -i "s/^CLAMPMSS=.*$/CLAMPMSS=Yes/" /etc/shorewall/shorewall.conf


# - integrate with fail2ban
sed -i "s/^BLACKLISTNEWONLY=.*$/BLACKLISTNEWONLY=No/" /etc/shorewall/shorewall.conf

# - deshabilitar ip-forwarding:
sed -i "s/^IP_FORWARDING=.*$/IP_FORWARDING=No/" /etc/shorewall/shorewall.conf

# deteccion de la primera interfaz
firstiface=$(ip route | grep default |  awk '{ print $5}' | tr -d ' ')

# configure shorewall
cat > /etc/shorewall/interfaces << EOF
############################################################################
# Shorewall interfaces
FORMAT 2
#ZONE   INTERFACE   OPTIONS
lan     $firstiface        routefilter,tcpflags,nosmurfs,logmartians,sourceroute=0
EOF

#### common files

# zones
cat > /etc/shorewall/zones << EOF
############################################################################
# Shorewall Zones
#ZONE   TYPE    OPTIONS         IN          OUT
#                   OPTIONS         OPTIONS
fw  firewall
lan ipv4
EOF

# policies
cat > /etc/shorewall/policy << EOF
############################################################################
# shorewall policies
#SOURCE     DEST        POLICY      LOG LEVEL   LIMIT:BURST
fw      lan     ACCEPT
# acceso desde lan
lan     fw      ACCEPT
# The FOLLOWING POLICY MUST BE LAST
all     all     DROP      info
EOF

# and rules
sshport=$(cat /etc/ssh/sshd_config | grep Port | cut -d ' ' -f2)
cat > /etc/shorewall/rules << EOF
#ACTION     SOURCE  DEST    PROTO   DEST   SOURCE  ORIGINAL RATE   USER/  MARK
#                                   PORT   PORT(S) DEST     LIMIT  GROUP
#
# Accept Ping and Traceroute from the internet
ACCEPT:info lan     fw     icmp       8
# Accept NTP udp
ACCEPT    lan     fw    udp     123
# SSH Access
ACCEPT      all     fw     tcp        $sshport    -    -   2/min:3

# Accept PING
Ping(ACCEPT)     lan     all

# open ports (multiport)
ACCEPT        all        fw       tcp      $TCP_PORTS
ACCEPT        all        fw       udp      $UDP_PORTS
EOF


### DDOS-Deflate Configuration


### install logger for shorewall
install_package fwlogwatch
## TODO: configurarlo para shorewall
